//! Preliminary MNT4/MNT6 cycle-native layer for the dissertation.
//!
//! This crate is deliberately narrower than a production CycleFold implementation.
//! It provides reproducible checks for the MNT4-753/MNT6-753 field cycle, reference
//! pairings through arkworks, and an explicit operation/constraint accounting model
//! for the relation fragments that would later be folded in a cycle-native proof.

use ark_ec::{pairing::Pairing, CurveGroup, PrimeGroup};
use ark_ff::{BigInteger, PrimeField};
use ark_mnt4_753::{Fq as Mnt4Fq, Fr as Mnt4Fr, G1Projective as Mnt4G1, G2Projective as Mnt4G2, MNT4_753};
use ark_mnt6_753::{Fq as Mnt6Fq, Fr as Mnt6Fr, G1Projective as Mnt6G1, G2Projective as Mnt6G2, MNT6_753};
use ark_serialize::CanonicalSerialize;
use serde::{Deserialize, Serialize};
use std::fmt::Write;

pub const MNT4_MILLER_ROUNDS: u64 = 376;
pub const MNT4_ADDITION_STEPS: u64 = 124;

// The MNT6 side is used here as a preliminary operation model for the opposite
// side of the cycle. The constants are derived from the arkworks ate-loop shape:
// one doubling transition for each processed non-leading loop digit, and an addition
// transition for every non-zero processed digit. The executable Solidity paths
// use 376 doubling transitions. MNT4 has 124 addition transitions, while MNT6
// has 123 addition transitions.
pub const MNT6_MILLER_ROUNDS: u64 = 376;
pub const MNT6_ADDITION_STEPS: u64 = 123;

pub const BN254_NON_NATIVE_SPARSE_MILLER_CONSTRAINTS: u64 = 63_309_128;
pub const SONOBE_LIKE_DECIDER_REFERENCE_CONSTRAINTS: u64 = 9_000_000;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CurveSide {
    Mnt4,
    Mnt6,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CycleFieldEqualities {
    pub fr_mnt4_equals_fq_mnt6: bool,
    pub fr_mnt6_equals_fq_mnt4: bool,
    pub mnt4_fq_bits: u32,
    pub mnt4_fr_bits: u32,
    pub mnt6_fq_bits: u32,
    pub mnt6_fr_bits: u32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RelationSideReport {
    pub side: CurveSide,
    pub base_field_bits: u32,
    pub scalar_field_bits: u32,
    pub embedding_degree: u64,
    pub miller_rounds: u64,
    pub addition_steps: u64,
    pub native_base_mul_constraints: u64,
    pub fq2_mul_constraints: Option<u64>,
    pub fq3_mul_constraints: Option<u64>,
    pub fq4_mul_constraints: Option<u64>,
    pub fq6_mul_constraints: Option<u64>,
    pub sparse_line_mul_constraints: u64,
    pub one_miller_transition_constraints: u64,
    pub miller_transition_constraints: u64,
    pub line_cache_relation_constraints: u64,
    pub fe_residue_constraints: u64,
    pub prepared_relation_constraints: u64,
    pub reference_pairing_digest: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CycleFullReport {
    pub field_equalities: CycleFieldEqualities,
    pub mnt4: RelationSideReport,
    pub mnt6: RelationSideReport,
    pub bn254_non_native_sparse_miller_constraints: u64,
    pub sonobe_like_decider_reference_constraints: u64,
    pub evm_gas_note: String,
}

pub fn check_cycle_field_equalities() -> CycleFieldEqualities {
    CycleFieldEqualities {
        fr_mnt4_equals_fq_mnt6: modulus_bytes::<Mnt4Fr>() == modulus_bytes::<Mnt6Fq>(),
        fr_mnt6_equals_fq_mnt4: modulus_bytes::<Mnt6Fr>() == modulus_bytes::<Mnt4Fq>(),
        mnt4_fq_bits: Mnt4Fq::MODULUS_BIT_SIZE,
        mnt4_fr_bits: Mnt4Fr::MODULUS_BIT_SIZE,
        mnt6_fq_bits: Mnt6Fq::MODULUS_BIT_SIZE,
        mnt6_fr_bits: Mnt6Fr::MODULUS_BIT_SIZE,
    }
}

pub fn mnt4_reference_pairing_digest() -> String {
    let p = Mnt4G1::generator().into_affine();
    let q = Mnt4G2::generator().into_affine();
    pairing_digest(MNT4_753::pairing(p, q))
}

pub fn mnt6_reference_pairing_digest() -> String {
    let p = Mnt6G1::generator().into_affine();
    let q = Mnt6G2::generator().into_affine();
    pairing_digest(MNT6_753::pairing(p, q))
}

pub fn build_cycle_report() -> CycleFullReport {
    let field_equalities = check_cycle_field_equalities();
    CycleFullReport {
        field_equalities,
        mnt4: mnt4_relation_report(),
        mnt6: mnt6_relation_report(),
        bn254_non_native_sparse_miller_constraints: BN254_NON_NATIVE_SPARSE_MILLER_CONSTRAINTS,
        sonobe_like_decider_reference_constraints: SONOBE_LIKE_DECIDER_REFERENCE_CONSTRAINTS,
        evm_gas_note: "F6B does not introduce a new EVM verifier. Gas is inherited from F4/F5 Solidity measurements; this module measures cycle-native relation fragments and reference pairings.".to_string(),
    }
}

pub fn render_markdown_report() -> String {
    let r = build_cycle_report();
    let mut out = String::new();
    writeln!(out, "# MNT4/MNT6 cycle-native preliminary report\n").unwrap();
    writeln!(out, "This report is generated by `mnt_cycle_full`. It is not a full CycleFold implementation and not a standalone EVM verifier. It records the implemented reference checks and the operation/constraint accounting for the future MNT-cycle-native relation layer.\n").unwrap();
    writeln!(out, "## Field cycle\n").unwrap();
    writeln!(out, "| Equality | Holds |").unwrap();
    writeln!(out, "|---|---:|").unwrap();
    writeln!(out, "| Fr(MNT4-753) = Fq(MNT6-753) | {} |", r.field_equalities.fr_mnt4_equals_fq_mnt6).unwrap();
    writeln!(out, "| Fr(MNT6-753) = Fq(MNT4-753) | {} |", r.field_equalities.fr_mnt6_equals_fq_mnt4).unwrap();
    writeln!(out, "\n| Field | Bits |").unwrap();
    writeln!(out, "|---|---:|").unwrap();
    writeln!(out, "| Fq(MNT4) | {} |", r.field_equalities.mnt4_fq_bits).unwrap();
    writeln!(out, "| Fr(MNT4) | {} |", r.field_equalities.mnt4_fr_bits).unwrap();
    writeln!(out, "| Fq(MNT6) | {} |", r.field_equalities.mnt6_fq_bits).unwrap();
    writeln!(out, "| Fr(MNT6) | {} |", r.field_equalities.mnt6_fr_bits).unwrap();
    writeln!(out, "\n## Reference pairings\n").unwrap();
    writeln!(out, "| Side | Digest prefix |").unwrap();
    writeln!(out, "|---|---|").unwrap();
    writeln!(out, "| MNT4 pairing(generator, generator) | {} |", short_digest(&r.mnt4.reference_pairing_digest)).unwrap();
    writeln!(out, "| MNT6 pairing(generator, generator) | {} |", short_digest(&r.mnt6.reference_pairing_digest)).unwrap();
    writeln!(out, "\n## Cycle-native relation accounting\n").unwrap();
    writeln!(out, "| Side | Tower | Miller rounds | Addition steps | One transition | Miller relation | Line-cache relation | FE residue | Prepared relation |").unwrap();
    writeln!(out, "|---|---|---:|---:|---:|---:|---:|---:|---:|").unwrap();
    write_side_row(&mut out, &r.mnt4, "Fq2/Fq4");
    write_side_row(&mut out, &r.mnt6, "Fq3/Fq6");
    writeln!(out, "\n## Comparison anchors\n").unwrap();
    writeln!(out, "| Scenario | Constraints / operation count |").unwrap();
    writeln!(out, "|---|---:|").unwrap();
    writeln!(out, "| MNT4 cycle-native prepared relation | {} |", r.mnt4.prepared_relation_constraints).unwrap();
    writeln!(out, "| MNT6 cycle-native prepared relation, preliminary | {} |", r.mnt6.prepared_relation_constraints).unwrap();
    writeln!(out, "| BN254 non-native sparse Miller estimate | {} |", r.bn254_non_native_sparse_miller_constraints).unwrap();
    writeln!(out, "| Sonobe/CycleFold-like decider reference anchor | {} |", r.sonobe_like_decider_reference_constraints).unwrap();
    writeln!(out, "\n## Gas boundary\n").unwrap();
    writeln!(out, "{}\n", r.evm_gas_note).unwrap();
    out
}

fn mnt4_relation_report() -> RelationSideReport {
    let fq2_mul = 3;
    let fq2_sqr = 2;
    let fq4_mul = 3 * fq2_mul;
    let fq4_sqr = 2 * fq2_sqr;
    let sparse_line = 2 * fq2_mul;
    let one_transition = fq4_sqr + sparse_line;
    let miller = MNT4_MILLER_ROUNDS * fq4_sqr + (MNT4_MILLER_ROUNDS + MNT4_ADDITION_STEPS) * sparse_line;
    let line_cache = MNT4_MILLER_ROUNDS * (14 * fq2_mul) + MNT4_ADDITION_STEPS * (10 * fq2_mul);
    let fe_residue = 5 * (2 * fq4_mul + fq4_sqr);
    RelationSideReport {
        side: CurveSide::Mnt4,
        base_field_bits: Mnt4Fq::MODULUS_BIT_SIZE,
        scalar_field_bits: Mnt4Fr::MODULUS_BIT_SIZE,
        embedding_degree: 4,
        miller_rounds: MNT4_MILLER_ROUNDS,
        addition_steps: MNT4_ADDITION_STEPS,
        native_base_mul_constraints: 1,
        fq2_mul_constraints: Some(fq2_mul),
        fq3_mul_constraints: None,
        fq4_mul_constraints: Some(fq4_mul),
        fq6_mul_constraints: None,
        sparse_line_mul_constraints: sparse_line,
        one_miller_transition_constraints: one_transition,
        miller_transition_constraints: miller,
        line_cache_relation_constraints: line_cache,
        fe_residue_constraints: fe_residue,
        prepared_relation_constraints: miller + line_cache + fe_residue,
        reference_pairing_digest: mnt4_reference_pairing_digest(),
    }
}

fn mnt6_relation_report() -> RelationSideReport {
    let fq3_mul = 6;
    let fq3_sqr = 5;
    let fq6_mul = 3 * fq3_mul;
    let fq6_sqr = 2 * fq3_sqr;
    let sparse_line = 2 * fq3_mul;
    let one_transition = fq6_sqr + sparse_line;
    let miller = MNT6_MILLER_ROUNDS * fq6_sqr + (MNT6_MILLER_ROUNDS + MNT6_ADDITION_STEPS) * sparse_line;
    let line_cache = MNT6_MILLER_ROUNDS * (14 * fq3_mul) + MNT6_ADDITION_STEPS * (10 * fq3_mul);
    let fe_residue = 5 * (2 * fq6_mul + fq6_sqr);
    RelationSideReport {
        side: CurveSide::Mnt6,
        base_field_bits: Mnt6Fq::MODULUS_BIT_SIZE,
        scalar_field_bits: Mnt6Fr::MODULUS_BIT_SIZE,
        embedding_degree: 6,
        miller_rounds: MNT6_MILLER_ROUNDS,
        addition_steps: MNT6_ADDITION_STEPS,
        native_base_mul_constraints: 1,
        fq2_mul_constraints: None,
        fq3_mul_constraints: Some(fq3_mul),
        fq4_mul_constraints: None,
        fq6_mul_constraints: Some(fq6_mul),
        sparse_line_mul_constraints: sparse_line,
        one_miller_transition_constraints: one_transition,
        miller_transition_constraints: miller,
        line_cache_relation_constraints: line_cache,
        fe_residue_constraints: fe_residue,
        prepared_relation_constraints: miller + line_cache + fe_residue,
        reference_pairing_digest: mnt6_reference_pairing_digest(),
    }
}

fn modulus_bytes<F: PrimeField>() -> Vec<u8> {
    F::MODULUS.to_bytes_le()
}

fn pairing_digest<P: Pairing>(value: ark_ec::pairing::PairingOutput<P>) -> String {
    let mut bytes = Vec::new();
    value.serialize_compressed(&mut bytes).expect("pairing output serialization must succeed");
    to_hex(&bytes)
}

fn to_hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(2 + bytes.len() * 2);
    out.push_str("0x");
    for b in bytes {
        write!(&mut out, "{b:02x}").unwrap();
    }
    out
}

fn short_digest(value: &str) -> String {
    if value.len() <= 34 {
        value.to_string()
    } else {
        format!("{}...{}", &value[..18], &value[value.len() - 12..])
    }
}

fn write_side_row(out: &mut String, r: &RelationSideReport, tower: &str) {
    writeln!(
        out,
        "| {:?} | {} | {} | {} | {} | {} | {} | {} | {} |",
        r.side,
        tower,
        r.miller_rounds,
        r.addition_steps,
        r.one_miller_transition_constraints,
        r.miller_transition_constraints,
        r.line_cache_relation_constraints,
        r.fe_residue_constraints,
        r.prepared_relation_constraints
    )
    .unwrap();
}
